#:import random random
<ScatterTextWidget>:
  orientation: 'vertical'
  TextInput:
    id: myTextInput
    font_size: 150
    size_hint_y: None
    height: 200
    text: 'default'
    # on_text: root.change_label_color()
    on_text: my_label.color = [random.random() for i in xrange(3)] + [1]
  FloatLayout:
    Scatter:
      Label:
        id: my_label
        text: myTextInput.text
        font_size: 150
